config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"

  resources :users
  resources :categories, only: [:index, :show, :new, :create, :update, :destroy] do
    resources :payments, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  resources :splash, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Category, user_id: user.id
      can :manage, Payment, user_id: user.id
      can :destroy, Category do |cat|
        cat.user_id == user.id
      end
      can :destroy, Payment do |pay|
        pay.user_id == user.id
      end
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :payments
  validates :name, presence: true, length: { maximum: 250 }
  has_one_attached :icon

  def total_payments
    payments.sum(:amount)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :payments
  validates :name, presence: true, length: { maximum: 250 }

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :require_login

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end

  private

  def require_login
    redirect_to splash_index_path if !current_user && (request.url == root_url)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(created_at: :desc).all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @payments = @category.payments.order(created_at: :desc).all
    @total_payments = @category.total_payments
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.user = current_user
    @payment.category_id = params[:category_id]
    if @payment.save
      redirect_to category_path(params[:category_id])
    else
      render :new
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, :category_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<main>
  <div class="app_header">
    <%= link_to "#", class: "btn_open_menu", id: "logout_btn" do%>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg>
    <% end %>
    <h2>Categories</h2>
    <%= link_to "Add new", new_category_path, class: "btn_add_new" %>
  </div>
  <div class="app_content">
    <% @categories.each do |category| %>
      <% if can? :manage, category %>
        <%= link_to category_path(category.id), class:"category_link" do %>
          <div class="category_details">
            <div class="category_photo">
              <% if category.icon.attached? %>
                <img src="<%= url_for(category.icon) %>" alt="<%= category.name %>">
              <% else %>
                <img src="/assets/logo.png" alt="logo" class="no_category_icon" />
              <% end %>
            </div>
            <div class="category_name fix_span">
              <h2><span><%= category.name %></span><span class="total_color">$ <%= category.total_payments %></span></h2>
              <hr class="category_hr">
              <h4><%= category.created_at.strftime("%d %b %Y") %></h4>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div id="myModal" class="modal">
    <div class="modal-content">
      <span class="close">&times;</span>
      <% if user_signed_in? %>
        <div>Hello <%= current_user.name %>!</div>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, data: { turbo: false }, class:"btn_signout_from" %>
      <% end %>
    </div>
  </div>
</main>

<script>
var modal = document.getElementById("myModal");

var btn = document.getElementById("logout_btn");

var span = document.getElementsByClassName("close")[0];

btn.onclick = function() {
  modal.style.display = "block";
}

span.onclick = function() {
  modal.style.display = "none";
}

window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>

app/views/categories/new.html.erb
<%= form_with model: @category, url: categories_path, local: true, html: { multipart: true } do |f| %>

  <div class="app_header">
    <%= link_to :back, class: "btn_open_menu" do%>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
    <% end %>
    <h2>Categories</h2>
    <%= f.submit "Add" %>
  </div>
  <div class="post_form_element">
    <%= f.text_field :name, class:"input_from", placeholder: "Name", autofocus: true %>
    <%= f.file_field :icon, class:"input_from" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<main>
  <div class="app_header">
    <%= link_to categories_path, class: "btn_open_menu" do%>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
    <% end %>
    <h2>Transactions</h2>
    <%= link_to "Add new", new_category_payment_path(@category.id), class: "btn_add_new" %>
  </div>
  <div class="app_content fix_gap">
    <% if can? :manage, @category %>
        <div class="category_details">
          <div class="category_photo">
            <% if @category.icon.attached? %>
              <img src="<%= url_for(@category.icon) %>" alt="<%= @category.name %>">
            <% else %>
              <img src="/assets/logo.png" alt="logo" class="no_category_icon" />
            <% end %>
          </div>
          <div class="category_name fix_align">
            <h2><%= @category.name %></h2>
            <hr class="category_hr">
            <h4><span>TOTAL TRANSACTIONS</span><span>$ <%= @total_payments %></span></h4>
          </div>
        </div>
        <div class="payment_details">
          <% @payments.each do |payment| %>
            <hr class="category_hr">
            <div class="category_details fix_pad">
              <div class="payment_name">
                <h2><%= payment.name %></h2>
                <h4><%= payment.created_at.strftime("%d %b %Y  %H:%M") %></h4>
                <div class="payment_amount">
                  <h2>TOTAL PAYMENT</h2>
                  <h3>$ <%= payment.amount %></h3>
                </div>
              </div>
            </div>
          <% end %>
        </div>
    <% end %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPocket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/new.html.erb
<%= form_with model: @payment, url: category_payments_path, local: true do |f| %>

  <div class="app_header">
    <%= link_to :back, class: "btn_open_menu" do%>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
    <% end %>
    <h2>Transactions</h2>
    <%= f.submit "Add" %>
  </div>
  <div class="post_form_element">
    <%= f.text_field :name, class:"input_from", placeholder: "Name", autofocus: true %>
    <%= f.number_field :amount, min: 0, class:"input_from", placeholder: "Amount" %>
  </div>
<% end %>

app/views/splash/index.html.erb
<main class="splash">
  <div class="app_logo">
    <img src="/assets/logo.png" alt="logo" />
    <h1>My Pocket</h1>
  </div>
  <p class="notice fix_notice"><%= notice %></p>
  <p class="alert fix_notice"><%= alert %></p>
  <div class="user_sign">
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Register", new_user_registration_path %>
  </div>
</main>